// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromotionService.Data;

#nullable disable

namespace PromotionService.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20260830101453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromotionService.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDiscountAmount")
                        .HasColumnType("int");

                    b.Property<int>("MinOrderValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimitTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "FREESHIP",
                            Description = "Giảm 10.000đ phí ship",
                            DiscountType = "FIXED",
                            DiscountValue = 10000m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinOrderValue = 30000,
                            StartAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageCount = 0,
                            UsageLimitPerCustomer = 3,
                            UsageLimitTotal = 1000
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "GIAM10",
                            Description = "Giảm 10%, tối đa 20.000đ",
                            DiscountType = "PERCENT",
                            DiscountValue = 10m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 20000,
                            MinOrderValue = 0,
                            StartAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageCount = 0,
                            UsageLimitPerCustomer = 1
                        });
                });

            modelBuilder.Entity("PromotionService.Entities.PromotionCustomerUsage", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommittedCount")
                        .HasColumnType("int");

                    b.HasKey("PromotionId", "CustomerId");

                    b.ToTable("PromotionCustomerUsages");
                });

            modelBuilder.Entity("PromotionService.Entities.PromotionReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CommittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionReservations");
                });

            modelBuilder.Entity("PromotionService.Entities.PromotionReservation", b =>
                {
                    b.HasOne("PromotionService.Entities.Promotion", "Promotion")
                        .WithMany("Reservations")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PromotionService.Entities.Promotion", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
